import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f7f3eb',
  },
  content: {
    gap: 16,
    paddingHorizontal: 20,
  },
  header: {
    flex: 1,
    gap: 4,
  },
  headerRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  settingsButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#d7cec0',
    borderRadius: 14,
    borderWidth: 1,
    backgroundColor: '#ffffff',
    minHeight: 44,
    minWidth: 44,
  },
  settingsIconText: {
    color: '#191919',
    fontSize: 22,
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(25, 25, 25, 0.45)',
    paddingHorizontal: 20,
  },
  modalCard: {
    gap: 12,
    borderRadius: 18,
    backgroundColor: '#f7f3eb',
    padding: 18,
  },
  modalTitle: {
    color: '#191919',
    fontSize: 20,
    fontWeight: '800',
  },
  modalHint: {
    color: '#6d6a63',
    fontSize: 14,
    lineHeight: 20,
  },
  modalExample: {
    color: '#6d6a63',
    fontSize: 12,
    lineHeight: 18,
  },
  apiQrScanButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    borderColor: '#d7cec0',
    borderRadius: 14,
    borderWidth: 2,
    backgroundColor: '#ffffff',
    minHeight: 56,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  apiQrScanButtonText: {
    color: '#191919',
    fontSize: 15,
    fontWeight: '700',
  },
  barcodeHint: {
    color: '#4e4a43',
    fontSize: 14,
    fontWeight: '600',
  },
  barcodeHintEan8: {
    color: '#2f6b4f',
  },
  barcodeHintEan13: {
    color: '#2f5f8a',
  },
  barcodeHintInvalid: {
    color: '#a33d2f',
  },
  barcodeHintRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  barcodeApiStatus: {
    fontSize: 14,
    fontWeight: '600',
  },
  barcodeApiStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  barcodeApiStatusLoading: {
    color: '#6d6a63',
  },
  barcodeApiStatusFound: {
    color: '#2f6b4f',
  },
  barcodeApiStatusNotFound: {
    color: '#8a6d3b',
  },
  barcodeApiStatusError: {
    color: '#a33d2f',
  },
  title: {
    color: '#191919',
    fontSize: 30,
    fontWeight: '800',
  },
  subtitle: {
    color: '#6d6a63',
    fontSize: 16,
  },
  section: {
    gap: 8,
  },
  sectionCaption: {
    color: '#6d6a63',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  priceFieldRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    gap: 10,
  },
  priceField: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderColor: '#d7cec0',
    borderRadius: 18,
    borderWidth: 2,
    backgroundColor: '#ffffff',
    minHeight: 96,
    paddingHorizontal: 20,
  },
  barcodeScanButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#d7cec0',
    borderRadius: 18,
    borderWidth: 2,
    backgroundColor: '#ffffff',
    minHeight: 96,
    width: 96,
  },
  barcodeIcon: {
    alignItems: 'center',
    flexDirection: 'row',
    height: 40,
  },
  barcodeBar: {
    backgroundColor: '#191919',
    borderRadius: 1,
    height: 40,
  },
  priceText: {
    color: '#000000',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: -2,
  },
  currencyText: {
    color: '#000000',
    fontSize: 22,
    fontWeight: '900',
    marginLeft: 10,
  },
  sizeSelector: {
    flexDirection: 'row',
    gap: 8,
  },
  sizeButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#d7cec0',
    borderRadius: 14,
    borderWidth: 1,
    backgroundColor: '#ffffff',
    minHeight: 64,
    paddingHorizontal: 6,
    paddingVertical: 8,
  },
  selectedSizeButton: {
    borderColor: '#111111',
    backgroundColor: '#111111',
  },
  sizeButtonTitle: {
    color: '#191919',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  sizeButtonSubtitle: {
    color: '#6d6a63',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
    textAlign: 'center',
  },
  selectedSizeButtonText: {
    color: '#ffffff',
  },
  offsetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  offsetToolbar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  offsetHint: {
    color: '#6d6a63',
    fontSize: 13,
  },
  offsetPanel: {
    borderColor: '#d7cec0',
    borderRadius: 18,
    borderWidth: 2,
    backgroundColor: '#ffffff',
    padding: 12,
  },
  offsetControls: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  offsetSpacer: {
    width: '31.3%',
  },
  offsetButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '31.3%',
    borderRadius: 14,
    backgroundColor: '#ede6da',
    minHeight: 52,
  },
  offsetButtonText: {
    color: '#191919',
    fontSize: 24,
    fontWeight: '800',
  },
  offsetCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '31.3%',
    minHeight: 112,
    gap: 4,
  },
  offsetValue: {
    color: '#191919',
    fontSize: 14,
    fontWeight: '700',
  },
  printerCard: {
    gap: 8,
    borderRadius: 14,
    backgroundColor: '#ede6da',
    padding: 14,
  },
  printerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardTitle: {
    color: '#191919',
    fontSize: 16,
    fontWeight: '800',
  },
  status: {
    color: '#4e4a43',
    fontSize: 14,
  },
  printerText: {
    color: '#191919',
    fontSize: 13,
    fontWeight: '600',
  },
  networkIpField: {
    gap: 6,
  },
  networkIpLabel: {
    color: '#6d6a63',
    fontSize: 13,
    fontWeight: '700',
  },
  networkIpInput: {
    borderColor: '#d7cec0',
    borderRadius: 14,
    borderWidth: 1,
    backgroundColor: '#ffffff',
    color: '#191919',
    fontSize: 16,
    fontWeight: '600',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  smallButton: {
    borderRadius: 999,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  smallButtonText: {
    color: '#191919',
    fontSize: 13,
    fontWeight: '800',
  },
  keypad: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  key: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '31.3%',
    borderRadius: 18,
    backgroundColor: '#ffffff',
    minHeight: 64,
  },
  secondaryKey: {
    backgroundColor: '#ded6ca',
  },
  activeKey: {
    backgroundColor: '#1d4ed8',
  },
  keyText: {
    color: '#191919',
    fontSize: 30,
    fontWeight: '800',
  },
  activeKeyText: {
    color: '#ffffff',
  },
  printButtonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  printButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#111111',
    minHeight: 62,
  },
  printManyButtonActive: {
    backgroundColor: '#1d4ed8',
  },
  printButtonText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  pressed: {
    opacity: 0.65,
  },
  disabled: {
    opacity: 0.5,
  },
});
